/*
  -----------------------------------------------Even Fibonacci numbers--------------------------------------
  Problem 2

  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/
#include<iostream>
using namespace std;

main()
{
  long int t1 = 1, t2 = 2, sum = t1+t2;
  int n;
  cin >> n;

  long  int eSum=0;
  while(t1<=n)
    {
      if(t1 % 2 == 0)
	eSum+=t1;
      t1 = t2;
      t2 = sum;
      sum = t1+t2;
    }
  cout <<  eSum;
}
